create table users (
                       login varchar primary key,
                       pass varchar not null);

create table messages (
                          id integer primary key generated by default as identity,
                          login varchar not null,
                          message varchar);

